CREATE TABLE IF NOT EXISTS usuarios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL,
  correo VARCHAR(180) NOT NULL UNIQUE,
  clave TEXT NOT NULL,
  rol VARCHAR(40) NOT NULL DEFAULT 'docente',
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS espacios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL UNIQUE,
  tipo VARCHAR(40) NOT NULL,
  ubicacion VARCHAR(120) NOT NULL,
  capacidad INTEGER NOT NULL CHECK (capacidad > 0),
  activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS reservas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id),
  espacio_id INTEGER NOT NULL REFERENCES espacios(id),
  fecha DATE NOT NULL,
  hora_inicio TIME NOT NULL,
  hora_fin TIME NOT NULL,
  motivo TEXT NOT NULL,
  estado VARCHAR(40) NOT NULL DEFAULT 'confirmada',
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (hora_inicio < hora_fin)
);

CREATE INDEX IF NOT EXISTS indice_reservas_espacio_fecha
ON reservas (espacio_id, fecha, hora_inicio, hora_fin);

INSERT INTO usuarios (nombre, correo, clave, rol)
VALUES (
  'Coordinacion Academica',
  'coordinacion@universidad.edu',
  '5ac0852e770506dcd80f1a36d20ba7878bf82244b836d9324593bd14bc56dcb5',
  'administrador'
)
ON CONFLICT (correo) DO NOTHING;

INSERT INTO espacios (nombre, tipo, ubicacion, capacidad, activo)
VALUES
  ('Salon A101', 'salon', 'Edificio A', 35, TRUE),
  ('Laboratorio Redes', 'laboratorio', 'Edificio B', 25, TRUE),
  ('Auditorio Central', 'auditorio', 'Edificio C', 120, TRUE)
ON CONFLICT (nombre) DO NOTHING;
